=== snettem2/xml/book.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="bookdetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="ISBN" type="xs:integer"/>
                            <xs:element name="publisher" type="xs:string"/>
                            <xs:element name="price" type="xs:decimal"/>
                            <xs:element name="edition" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== snettem2/xml/Bookstore1.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="book.xsl"?>
<bookdetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="book.xsd">


<bookdetails>
    <book>
        <title>Data Structures</title>
        <author>S. Kumar</author>
        <ISBN>101</ISBN>
        <publisher>Pearson</publisher>
        <price>450</price>
        <edition>3</edition>
    </book>

    <book>
        <title>Operating Systems</title>
        <author>R. Sharma</author>
        <ISBN>102</ISBN>
        <publisher>McGraw Hill</publisher>
        <price>550</price>
        <edition>4</edition>
    </book>

    <book>
        <title>Computer Networks</title>
        <author>A. Verma</author>
        <ISBN>103</ISBN>
        <publisher>Oxford</publisher>
        <price>600</price>
        <edition>5</edition>
    </book>

    <book>
        <title>Database Systems</title>
        <author>P. Reddy</author>
        <ISBN>104</ISBN>
        <publisher>Springer</publisher>
        <price>500</price>
        <edition>2</edition>
    </book>
</bookdetails>
